---
# Source: argo-cd/templates/server/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-cd-argocd-server
  namespace: "argo-cd"
  labels:
    app.kubernetes.io/name: argo-cd
    helm.sh/chart: argo-cd-4.5.2
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: server
automountServiceAccountToken: true
