---
# Source: argo-cd/templates/application-controller/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: argo-cd-app-controller
  namespace: "argo-cd"
  labels:
    app.kubernetes.io/name: argo-cd
    helm.sh/chart: argo-cd-4.5.2
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: tcp-controller
      port: 8082
      targetPort: controller
      protocol: TCP
      nodePort: null
  selector:
    app.kubernetes.io/name: argo-cd
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/component: controller
