---
# Source: argo-cd/templates/repo-server/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: argo-cd-repo-server
  namespace: "argo-cd"
  labels:
    app.kubernetes.io/name: argo-cd
    helm.sh/chart: argo-cd-4.5.2
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: repo-server
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: tcp-repo-server
      port: 8081
      targetPort: repo-server
      protocol: TCP
      nodePort: null
  selector:
    app.kubernetes.io/name: argo-cd
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/component: repo-server
